### ISSUE TITLE
No module named 'batch_rename'

### ISSUE THREAD

**Issue by nothing2obvi** [hollanbm/sonarr-series-scanner#14]
My container keeps restarting, with the following error code:

```
05/10/2024
07:11:16 PM
ModuleNotFoundError: No module named 'batch_rename'
05/10/2024
07:11:24 PM
Traceback (most recent call last):
05/10/2024
07:11:24 PM
  File "/home/app/series_scanner/src/main.py", line 7, in <module>
05/10/2024
07:11:24 PM
    from existing_renamer import ExistingRenamer
05/10/2024
07:11:24 PM
  File "/home/app/series_scanner/src/existing_renamer.py", line 8, in <module>
05/10/2024
07:11:24 PM
    from batch_rename import BatchRename
05/10/2024
07:11:24 PM
ModuleNotFoundError: No module named 'batch_rename'
05/10/2024
07:11:34 PM
Traceback (most recent call last):
05/10/2024
07:11:34 PM
  File "/home/app/series_scanner/src/main.py", line 7, in <module>
05/10/2024
07:11:34 PM
    from existing_renamer import ExistingRenamer
05/10/2024
07:11:34 PM
  File "/home/app/series_scanner/src/existing_renamer.py", line 8, in <module>
05/10/2024
07:11:34 PM
    from batch_rename import BatchRename
```

**Comment by hollanbm** [comment]
> My container keeps restarting, with the following error code:
> 
> ```
> 05/10/2024
> 07:11:16 PM
> ModuleNotFoundError: No module named 'batch_rename'
> 05/10/2024
> 07:11:24 PM
> Traceback (most recent call last):
> 05/10/2024
> 07:11:24 PM
>   File "/home/app/series_scanner/src/main.py", line 7, in <module>
> 05/10/2024
> 07:11:24 PM
>     from existing_renamer import ExistingRenamer
> 05/10/2024
> 07:11:24 PM
>   File "/home/app/series_scanner/src/existing_renamer.py", line 8, in <module>
> 05/10/2024
> 07:11:24 PM
>     from batch_rename import BatchRename
> 05/10/2024
> 07:11:24 PM
> ModuleNotFoundError: No module named 'batch_rename'
> 05/10/2024
> 07:11:34 PM
> Traceback (most recent call last):
> 05/10/2024
> 07:11:34 PM
>   File "/home/app/series_scanner/src/main.py", line 7, in <module>
> 05/10/2024
> 07:11:34 PM
>     from existing_renamer import ExistingRenamer
> 05/10/2024
> 07:11:34 PM
>   File "/home/app/series_scanner/src/existing_renamer.py", line 8, in <module>
> 05/10/2024
> 07:11:34 PM
>     from batch_rename import BatchRename
> ```

Thanks for reporting. I added some unit tests, and got a little too confident.

I'll have a fix published shortly

**Comment by hollanbm** [comment]
@nothing2obvi `0.4.1` published, should resolve your issue.
